databricks_resources:
  catalog: dbdemos_merve
  checkpoint_volume: checkpoints
  checkpoint_volume_path: /Volumes/dbdemos_merve/dbdemos_large_document_rag/checkpoints
  child_table: dbdemos_merve.dbdemos_large_document_rag.documents_child_splits
  document_feature_spec: parent_document_spec
  document_feature_spec_uri: dbdemos_merve.dbdemos_large_document_rag.parent_document_spec
  document_table: dbdemos_merve.dbdemos_large_document_rag.documents
  embedding_endpoint_name: databricks-bge-large-en
  feature_serving_endpoint_name: dbdemos_large_document_rag-parent-splits
  host: https://e2-demo-field-eng.cloud.databricks.com
  llm_endpoint_name: databricks-dbrx-instruct
  parent_table: dbdemos_merve.dbdemos_large_document_rag.documents_parent_splits
  rag_chain_endpoint_name: dbdemos_large_document_rag-chain
  rag_chain_model_name: chain_model
  schema: dbdemos_large_document_rag
  source_volume: source_data
  source_volume_path: /Volumes/dbdemos_merve/dbdemos_large_document_rag/source_data/text
  vector_search_endpoint_name: one-env-shared-endpoint-2
  vector_search_index: dbdemos_merve.dbdemos_large_document_rag.documents_child_splits_index
input_example:
  messages:
  - content: What are the conditions of my insurance?
    filter: All Documents
    role: user
  - content: The conditions can vary based on the specic type of insurance
    filter: All Documents
    role: assistant
  - content: Tell me about the travel cancellation insurance.
    filter: Travel-Cancellation-Insurance
    role: user
llm_config:
  llm_parameters:
    max_tokens: 1500
    temperature: 0.01
  llm_prompt_template: 'You are a trusted assistant that helps answer questions based
    only on the provided information. If you do not know the answer to a question,
    you truthfully say you do not know.  Here is some context which might or might
    not help you answer: {context}.  Answer directly, do not repeat the question,
    do not start with something like: the answer to the question, do not add AI in
    front of your answer, do not say: here is the answer, do not mention the context
    or the question. Based on this context, answer this question: {question}'
  llm_prompt_template_variables:
  - context
  - question
retriever_config:
  child_splits_table_schema:
    child_split_index: child_split_index
    document_foreign_key: document_id
    document_name_col: document_name
    document_uri: url
    embedding_vector_col: embedding_vector
    parent_split_foreign_key: parent_split_id
    parent_split_index: parent_split_index
    primary_key: child_split_id
    text_col: content
    timestamp_col: timestamp
  chunk_template: 'Passage: {chunk_text}

    '
  data_pipeline_tag: poc
  document_table_schema:
    document_name_col: document_name
    document_uri: url
    primary_key: document_id
    text_col: content
    timestamp_col: timestamp
  embedding_dimension: 1024
  n_child_tokens: 1024
  n_parent_tokens: 8192
  parameters:
    k: 3
  parent_splits_table_schema:
    document_foreign_key: document_id
    document_name_col: document_name
    document_uri: url
    parent_split_index: parent_split_index
    primary_key: parent_split_id
    text_col: content
    timestamp_col: timestamp
secrets_config:
  secret_key: rag_sp_token
  secret_scope: dbdemos
